### ISSUE TITLE
运行stock.py出现如下错误

### ISSUE THREAD

**Issue by perfect-11** [lemonhu/stock-knowledge-graph#13]
Traceback (most recent call last):
  File "D:/PycharmProjects/untitled/stock-knowledge-graph-master/stock.py", line 1, in <module>
    import tushare as ts
  File "D:\PycharmProjects\untitled\venv\lib\site-packages\tushare\__init__.py", line 11, in <module>
    from tushare.stock.trading import (get_hist_data, get_tick_data,
  File "D:\PycharmProjects\untitled\venv\lib\site-packages\tushare\stock\trading.py", line 15, in <module>
    import pandas as pd
ImportError: No module named 'pandas'

请问怎么解决？

**Comment by TTiger-chen** [comment]
你应该是没安装Pandas包
